class AdditionalVariables:
    URL = 'https://stellarburgers.nomoreparties.site'
    URL_API_LOGIN = 'https://stellarburgers.nomoreparties.site/api/auth/login'
    URL_API_USER = 'https://stellarburgers.nomoreparties.site/api/auth/user'
    URL_API_REGISTER = 'https://stellarburgers.nomoreparties.site/api/auth/register'
    URL_API_INGREDIENTS = 'https://stellarburgers.nomoreparties.site/api/ingredients'
    URL_API_ORDERS = 'https://stellarburgers.nomoreparties.site/api/orders'

    ERROR_403_USER_ALREADY_EXISTS = 'User already exists'
    ERROR_403_FIELDS_REQUIRED = 'Email, password and name are required fields'
    ERROR_401_INCORRECT = 'email or password are incorrect'
    ERROR_401_NOT_AUTHORIZED = 'You should be authorised'
    ERROR_403_EMAIL_ALREADY_EXISTS = 'User with such email already exists'
    ERROR_400_NO_INGREDIENT = 'Ingredient ids must be provided'
    INCORRECT_HASH = 'test-hash'
